### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by daviddl9** [daviddl9/rfind#3]
###  Phase I - Core improvements
- [x] Add symlink handling options (-L/-H/-P)
- [x] Implement basic -type filtering
- [x] Add `-print0` output option

### Phase II - Common filters
- [x] Add time-based filters (-mtime, -atime, -ctime etc.)
- [x] Implement size filtering

### Phase III - Advanced features
- [ ] Community feedback - get requested features
- [ ] Code optimisations
